language: node_js
node_js:
- 6
before_install:
- npm install -g npm@latest
- wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
- tar jxf phantomjs-2.1.1-linux-x86_64.tar.bz2
- sudo cp -Raf --remove-destination phantomjs-*/* /usr/local/
- wget --retry-connrefused https://github.com/n1k0/casperjs/tarball/1.1.4-1
- tar zvxf 1.1.4-1
- sudo cp -Raf --remove-destination casperjs-casperjs-*/* /usr/local/
notifications:
  email: false
  slack:
    secure: gTNTTwFYpakA7O8yBhnk/cU3zP5lK2aHBkcTdiwmaNxbSNnfgQrrXlY8+ZBbEiAu83t7KZR50G8uX55SZ/QguVx8gMy5Acx1a+ihhZB83RAn1pmm56h3iNjD3EAcb3kjZrSaHTd50/27ZQLJIE/QGLMx+FNOjXQ5Rjl9pwev1DQ=
env:
  global:
    secure: WZ7d9RevZxdaBNafAhi+D7taEPgWUC1NzZ3cH1nNXJmKBwg4bDoQmpWr+d5UAdu/gmveqH/NpV74zxQlcj4svLpb0SKRh3pUdsm0FsisPfBBVelK9qzGmpAa4P2peuDJs1oVAjRypZsn4DHUmAXV7doTiE0F2NS1DrjCwQVi+KY=
before_script: npm run build
script: npm run test
