language: node_js
node_js:
- 6
before_install:
- npm install -g npm@latest
- wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
- tar jxf phantomjs-2.1.1-linux-x86_64.tar.bz2
- sudo cp -Raf --remove-destination phantomjs-*/* /usr/local/
- wget --retry-connrefused https://github.com/n1k0/casperjs/tarball/1.1.4-1
- tar zvxf 1.1.4-1
- sudo cp -Raf --remove-destination casperjs-casperjs-*/* /usr/local/
notifications:
  email: false
  slack:
    secure: gTNTTwFYpakA7O8yBhnk/cU3zP5lK2aHBkcTdiwmaNxbSNnfgQrrXlY8+ZBbEiAu83t7KZR50G8uX55SZ/QguVx8gMy5Acx1a+ihhZB83RAn1pmm56h3iNjD3EAcb3kjZrSaHTd50/27ZQLJIE/QGLMx+FNOjXQ5Rjl9pwev1DQ=
env:
- secure: B+Nha+TarsZCCoOYIyeMEFyiAWY/o7kgmyj9hwCBikOOoM/FLBrldW8E4DYhP2ub0xv/VtQywcMovDkPi+y4b5ooMnWodDYtDwzkOlyrDqNJIzsaT6KQ5Q7qsXVxEMK/RsLLrwRMlGZJiu1nqFsUJNVswmu4o71fb+Rnc6sXxbY=
before_script: npm run build
script: npm run test
TRANSLOADIT_ACCESS_KEY=8a0245b6411f553b98140491391144cb:
  secure: PptRG9SOn1HqqsV8c2nYETuKoGDkr6kuOwL1siO/1rk6KHN9lwkP8q5wDTuHH+awMPe66BZbbuJs6UCAj8/1YgrKwr5C0Kjl8RN/3Hz5oRRquz3O/Z2RfLtLt2H5ZApKH8bssKQidGzH6WVPfzALVhvq83bpWznkmtR6L1bcOJ8=
